# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('known_ip', models.CharField(max_length=64)),
                ('mac_address', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
