# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('netmon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='device',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
